import type { Metadata } from "next";
import styles from "./styles.module.css";
import "./reset.css";
import "./global.css";

export const metadata: Metadata = {
  title: "Cordoku",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <h1>Cordoku</h1>
        </header>
        <section className={styles.content}>{children}</section>
      </body>
    </html>
  );
}
